### ISSUE TITLE
Error Importing getPrivateKey

### ISSUE THREAD

**Issue by haupt-pascal** [Pymmdrza/cryptoFuzz#5]
Cheers! 

I am getting the following error while running a few tests of this package: 

Traceback (most recent call last):
  File "/root/test_py/test.py", line 2, in <module>
    from cryptofuzz import getPrivateKey, PrivateKey_To_Address
ImportError: cannot import name 'getPrivateKey' from 'cryptofuzz' (/usr/local/lib/python3.9/dist-packages/cryptofuzz/__init__.py)

Can you tell me what I exactly have to do? The same error comes on windows.

**Comment by Pymmdrza** [comment]
> Cheers!
> 
> I am getting the following error while running a few tests of this package:
> 
> Traceback (most recent call last): File "/root/test_py/test.py", line 2, in from cryptofuzz import getPrivateKey, PrivateKey_To_Address ImportError: cannot import name 'getPrivateKey' from 'cryptofuzz' (/usr/local/lib/python3.9/dist-packages/cryptofuzz/**init**.py)
> 
> Can you tell me what I exactly have to do? The same error comes on windows.

Can I see the sample code you use in its header? To give more guidance and help?

**Comment by Pymmdrza** [comment]
> Cheers!
> 
> I am getting the following error while running a few tests of this package:
> 
> Traceback (most recent call last): File "/root/test_py/test.py", line 2, in from cryptofuzz import getPrivateKey, PrivateKey_To_Address ImportError: cannot import name 'getPrivateKey' from 'cryptofuzz' (/usr/local/lib/python3.9/dist-packages/cryptofuzz/**init**.py)
> 
> Can you tell me what I exactly have to do? The same error comes on windows.

### Example:  

[ `cryptoFuzz/Example` ](https://github.com/Pymmdrza/cryptoFuzz/tree/main/Example)

**Comment by haupt-pascal** [comment]
`import threading
from cryptofuzz import getPrivateKey, PrivateKey_To_Address

def check_address(address):
    with open('rich.txt', 'r') as file:
        for line in file:
            if line.strip() == address:
                return True
    return False

def generate_address():
    private_key = getPrivateKey()
    address = PrivateKey_To_Address(private_key, compress=True)
    print(f"Generated address: {address}")
    return private_key, address

def search_address():
    while not found[0]:
        private_key, address = generate_address()
        if check_address(address):
            found[0] = True
            with open('found.txt', 'w') as file:
                file.write(f"Private Key: {private_key}\n")
                file.write(f"Address: {address}\n")
            print("Address found in rich.txt!")
            break

found = [False]
threads = []
for _ in range(4):
    thread = threading.Thread(target=search_address)
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()
`

I used the getPrivateKey from the documentation, isn't it the right way?

**Comment by Pymmdrza** [comment]
> `import threading
> from cryptofuzz import getPrivateKey, PrivateKey_To_Address
> 
> def check_address(address):
>     with open('rich.txt', 'r') as file:
>         for line in file:
>             if line.strip() == address:
>                 return True
>     return False
> 
> def generate_address():
>     private_key = getPrivateKey()
>     address = PrivateKey_To_Address(private_key, compress=True)
>     print(f"Generated address: {address}")
>     return private_key, address
> 
> def search_address():
>     while not found[0]:
>         private_key, address = generate_address()
>         if check_address(address):
>             found[0] = True
>             with open('found.txt', 'w') as file:
>                 file.write(f"Private Key: {private_key}\n")
>                 file.write(f"Address: {address}\n")
>             print("Address found in rich.txt!")
>             break
> 
> found = [False]
> threads = []
> for _ in range(4):
>     thread = threading.Thread(target=search_address)
>     threads.append(thread)
>     thread.start()
> 
> for thread in threads:
>     thread.join()
> `
> 
> I used the getPrivateKey from the documentation, isn't it the right way? 

```python

from cryptofuzz import Convertor, Generator


conv = Convertor()
gen = Generator()
# Generate private key
privatekey = gen.generate_private_key()
# Convert private key To bytes
seed = conv.hex_to_bytes(privatekey)
# Convert private key To mnemonic
mnemonic = conv.hex_to_mne(privatekey)
# Convert private key To wif compress
wif_compress = conv.hex_to_wif(privatekey, True)
# Convert private key To wif uncompress
wif_uncompress = conv.hex_to_wif(privatekey, False)
# Convert private key To decimal number
dec = conv.hex_to_int(privatekey)
# Convert private key To binary
binary_str = conv.hex_to_binary(privatekey)
# Convert private key To xprv
xprv = conv.hex_to_xprv(privatekey)
# Convert private key To xpub
xpub = conv.hex_to_xpub(privatekey)
# Convert private key To compress address
compress_address = conv.hex_to_addr(privatekey, True)
# Convert private key To uncompress address
uncompress_address = conv.hex_to_addr(privatekey, False)

print('Private key', privatekey)
print('Compress address', compress_address)
print('Uncompress address', uncompress_address)
print('Mnemonic', mnemonic)
print('Seed', seed)
print('WIF compress', wif_compress)
print('WIF uncompress', wif_uncompress)
print('Dec', dec)
print('Binary', binary_str)
print('XPRV', xprv)
print('XPUB', xpub)
```

**Comment by Pymmdrza** [comment]
Like that checked.
